# Generated by Django 4.0.1 on 2022-01-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_rename_projects_nemes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nemes',
            name='description',
            field=models.TextField(max_length=900),
        ),
    ]
