# Generated by Django 4.0.1 on 2022-01-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0004_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nemes',
        ),
    ]
