# Generated by Django 4.0.1 on 2022-01-16 01:03

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0006_remove_names_video_alter_names_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names_Allah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('Video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='names',
            name='Video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
